
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Explicit coordinates, not "auto".
--
-- `auto`/`auto-right` place monitors in enumeration order, and that order
-- depends on which GPU is primary. Making the dGPU primary for gaming flipped
-- it: HDMI-A-2 landed at 0,0 and the laptop panel ended up on the *right*,
-- so moving the cursor left off the big screen hit nothing.
--
-- eDP-1 is 1920x1080 at scale 1.5, i.e. 1280x720 logical — so HDMI-A-2
-- starts at x=1280, immediately to its right. Layout is now fixed regardless
-- of GPU order or plug-in sequence.
hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@360",
    position = "0x0",
    scale    = 1.5,
})

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "2560x1440@144",
    position = "1280x0",
    scale    = 1,
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "alacritty"
local fileManager = "thunar"
local menu        = "~/.config/themes/launch.sh"  -- per-rice launcher


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
 hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
   -- swww replaces hyprpaper: it animates wallpaper changes, and each rice
   -- picks its own transition (see themes/<n>/wallpaper). switch.sh falls
   -- back to hyprpaper automatically if the swww daemon is not running, so
   -- this is safe either way.
   hl.exec_cmd("swww-daemon || awww-daemon || hyprpaper")
   hl.exec_cmd("waybar")
   hl.exec_cmd("mako")           -- notification daemon, see ~/.config/mako/config
   hl.exec_cmd("hypridle")       -- idle -> lock, see ~/.config/hypr/hypridle.conf
 end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")

-- ── GPU selection (gaming) ─────────────────────────────────────────────
-- This is a hybrid laptop: Intel UHD (00:02.0) + RTX 3070 Mobile (01:00.0).
-- HDMI-A-2 — the 1440p144 ASUS VG27WQ — is wired to the *NVIDIA* card, but
-- aquamarine picks the iGPU as primary by default. The log then shows
-- "GBM: Buffer is marked as multigpu, forcing linear": every frame for that
-- monitor is composited on Intel and copied to NVIDIA through an untiled
-- buffer. At 2560x1440@144 that copy is exactly the wrong thing to be doing.
--
-- Listing the dGPU first makes it the primary renderer, so frames are drawn
-- on the card the monitor is attached to and scanned out directly.
--
-- AQ_DRM_DEVICES is a COLON-separated list, and PCI paths contain colons.
-- Passing /dev/dri/by-path/pci-0000:01:00.0-card directly gets split into
-- "/dev/dri/by-path/pci-0000", "01" and "00.0-card" -- aquamarine then logs
-- "Found no gpus to use, cannot continue" and the session never starts.
-- (That is exactly what happened here once already.)
--
-- So: resolve by-path to /dev/dri/cardN at config-parse time. That keeps the
-- stability of by-path — cardN numbering is not guaranteed across reboots —
-- while handing aquamarine a string with no colons in the names.
--
-- The guard is deliberately strict: unless BOTH cards resolve to a plain
-- /dev/dri/cardN, the variable is left unset and Hyprland picks its own
-- default. A bad value here costs you the whole session, so failing closed
-- is the only sane behaviour.
--
-- TRADE-OFF: the desktop then renders on the dGPU, which costs battery.
-- Set gpuPreferDedicated to false below to go back to the iGPU for travel.
local gpuPreferDedicated = true

local function drmCardFor(pci)
    local f = io.popen("readlink -f /dev/dri/by-path/pci-" .. pci .. "-card 2>/dev/null")
    if not f then return nil end
    local path = f:read("l")
    f:close()
    if not path or not path:match("^/dev/dri/card%d+$") then return nil end
    return path
end

if gpuPreferDedicated then
    local dgpu = drmCardFor("0000:01:00.0")   -- RTX 3070, drives HDMI-A-2
    local igpu = drmCardFor("0000:00:02.0")   -- Intel UHD, drives eDP-1
    if dgpu and igpu then
        hl.env("AQ_DRM_DEVICES", dgpu .. ":" .. igpu)
    else
        io.stderr:write("hyprland.lua: GPU paths did not resolve; " ..
                        "leaving AQ_DRM_DEVICES unset\n")
    end
end

-- Let games and Steam target the dGPU explicitly.
hl.env("__NV_PRIME_RENDER_OFFLOAD", "1")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
-- Styling (gaps, borders, rounding, blur, shadow) comes from the active rice
-- at ~/.config/themes/current/hypr.lua; behaviour stays here. Switching a
-- profile repoints that symlink and runs `hyprctl reload`, which re-runs this
-- file and picks up the new values.
--
-- pcall'd on purpose: a broken or dangling theme must not take the whole
-- config down with it. Worst case we fall back to Hyprland's own defaults
-- and the session still comes up.
local themePath = os.getenv("HOME") .. "/.config/themes/current/hypr.lua"
local themeOk, theme = pcall(dofile, themePath)
if not themeOk or type(theme) ~= "table" then
    io.stderr:write("hyprland.lua: could not load theme " .. themePath .. "\n")
    theme = {}
end

local function withTheme(behaviour, styling)
    local out = {}
    for k, v in pairs(behaviour) do out[k] = v end
    for k, v in pairs(styling or {}) do out[k] = v end
    return out
end

hl.config({
    general = withTheme({
        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Tearing is opt-in per window, not global: enabling it here only
        -- permits it, and nothing tears until a window carries the
        -- `immediate` rule. The game rules further down set that, so this
        -- buys lower input latency in fullscreen games and changes nothing
        -- anywhere else.
        -- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/
        allow_tearing = true,

        layout = "dwindle",
    }, theme.general),

    decoration = withTheme({}, theme.decoration),

    animations = {
        enabled = true,
    },
})

-- Motion is part of the rice, not a constant: a glassy theme wants long
-- eased fades, a CRT theme wants everything to snap. Each profile ships its
-- own curves + animation table in themes/current/hypr.lua, applied here.
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
--
-- A theme that omits either falls back to the stock set below, so an
-- animation-less theme file is still valid.

local defaultCurves = {
    { name = "easeOutQuint",   type = "bezier", points = { {0.23, 1},    {0.32, 1}    } },
    { name = "easeInOutCubic", type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } },
    { name = "linear",         type = "bezier", points = { {0, 0},       {1, 1}       } },
    { name = "almostLinear",   type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } },
    { name = "quick",          type = "bezier", points = { {0.15, 0},    {0.1, 1}     } },
    { name = "easy",           type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 },
}

local defaultAnimations = {
    { leaf = "global",        enabled = true, speed = 10,   bezier = "default" },
    { leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" },
    { leaf = "windows",       enabled = true, speed = 4.79, spring = "easy" },
    { leaf = "windowsIn",     enabled = true, speed = 4.1,  spring = "easy",         style = "popin 87%" },
    { leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" },
    { leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" },
    { leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" },
    { leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" },
    { leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" },
    { leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" },
    { leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" },
    { leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" },
    { leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" },
    { leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" },
    { leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" },
    { leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" },
    { leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" },
}

for _, c in ipairs(theme.curves or defaultCurves) do
    if c.type == "spring" then
        hl.curve(c.name, { type = "spring", mass = c.mass,
                           stiffness = c.stiffness, dampening = c.dampening })
    else
        hl.curve(c.name, { type = "bezier", points = c.points })
    end
end

for _, a in ipairs(theme.animations or defaultAnimations) do
    hl.animation(a)
end

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(

        -- VRR mode 2 = fullscreen only. The VG27WQ is a FreeSync panel, so a
        -- game rendering below 144fps gets a matched refresh instead of
        -- judder. Restricted to fullscreen because desktop-wide VRR makes
        -- some panels flicker on static content.
        vrr = 2,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Rice picker (rofi menu over all profiles, styled by the active rice)
hl.bind(mainMod .. " + T",             hl.dsp.exec_cmd("~/.config/themes/picker.sh"))

-- Quickshell surfaces on rices that ship one (qshell, calamity). Reached over
-- IPC rather than Quickshell's GlobalShortcut: that registers an action, and
-- binding it needs a `global` dispatcher this Lua wrapper does not expose.
-- qsipc.sh exits quietly on the rices with no Quickshell shell, so these are
-- harmless everywhere else.
hl.bind(mainMod .. " + SPACE",         hl.dsp.exec_cmd("~/.config/themes/qsipc.sh palette toggle"))
hl.bind(mainMod .. " + D",             hl.dsp.exec_cmd("~/.config/themes/qsipc.sh dash toggle"))

-- Screenshots. grim writes the file, slurp picks the region, swappy annotates.
-- Region shots go straight to swappy so you can mark up before saving; the
-- full-screen one just files it and copies to the clipboard.
hl.bind(mainMod .. " + SHIFT + S",     hl.dsp.exec_cmd(
    "grim -g \"$(slurp)\" - | swappy -f -"))
hl.bind("Print",                       hl.dsp.exec_cmd(
    "mkdir -p ~/Pictures/Screenshots && f=~/Pictures/Screenshots/$(date +%Y%m%d-%H%M%S).png "
    .. "&& grim \"$f\" && wl-copy < \"$f\""))

-- Lock now (hyprlock is themed per rice, see themes/<n>/hyprlock.conf)
hl.bind(mainMod .. " + L",             hl.dsp.exec_cmd("hyprlock"))

-- Status HUD. Some rices (mono, eink) deliberately run no panel at all —
-- this is their status bar, summoned on demand. Works on every rice.
hl.bind(mainMod .. " + I",             hl.dsp.exec_cmd("~/.config/waybar/scripts/hud.sh"))

-- Notifications (mako)
hl.bind(mainMod .. " + N",             hl.dsp.exec_cmd("makoctl dismiss"))
hl.bind(mainMod .. " + SHIFT + N",     hl.dsp.exec_cmd("makoctl mode -t do-not-disturb"))
hl.bind(mainMod .. " + CTRL + N",      hl.dsp.exec_cmd("makoctl restore"))
hl.bind(mainMod .. " + ALT + N",       hl.dsp.exec_cmd("makoctl dismiss --all"))

hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- ── Games ──────────────────────────────────────────────────────────────
-- Every rice sets blur, shadows, rounding, opacity and animations. None of
-- that should be running over a fullscreen game: it costs GPU time on the
-- same card that is trying to hold 144fps, and rounding on a fullscreen
-- window is invisible anyway. These rules strip the compositor back to a
-- plain scanout for games regardless of which profile is active.
--
-- `immediate` is what actually enables tearing (general.allow_tearing only
-- permits it) — it lets a finished frame be scanned out mid-refresh instead
-- of waiting, which is the latency win.
hl.window_rule({
    name  = "games-no-effects",
    match = { fullscreen = true },

    no_blur   = true,
    no_shadow = true,
    no_anim   = true,
    rounding  = 0,
    immediate = true,
})

-- Steam's own chrome: the client, the overlay and the big-picture window
-- float badly by default and pick up the rice's blur for no benefit.
hl.window_rule({
    name  = "steam-client",
    match = { class = "^steam$" },

    no_blur = true,
})

hl.window_rule({
    -- Steam's notification/overlay popups have no title and misbehave when
    -- tiled; float them and keep focus on the game.
    name  = "steam-popups",
    match = { class = "^steam$", title = "^$" },

    float    = true,
    no_focus = true,
})

-- mako toasts — blur behind the translucent pill so they read the same
-- as waybar's islands over a busy wallpaper. ignore_alpha skips the fully
-- transparent gaps between stacked notifications, which would otherwise
-- render as blurred rectangles.
hl.layer_rule({
    name  = "blur-notifications",
    match = { namespace = "^notifications$" },

    blur         = true,
    ignore_alpha = 0.5,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- nmtui, launched from the waybar network module — float it as a panel
-- under the bar instead of tiling into the workspace.
hl.window_rule({
    name  = "float-nm-tui",
    match = { class = "nm-float" },

    float = true,
    size  = "620 420",
    move  = "monitor_w-640 40",
})
