# Mac OS X — hyprlock
background {
    monitor =
    path = /home/birch/Pictures/Wallpapers/themes/macos.png
    blur_passes = 3
    blur_size = 8
    brightness = 0.5
}
input-field {
    monitor =
    size = 300, 48
    outline_thickness = 2
    dots_center = true
    outer_color = rgba(0a84ffff)
    inner_color = rgba(2c2c2ee6)
    font_color = rgba(ffffffff)
    placeholder_text = <span foreground="##8e8e93">Enter Password</span>
    rounding = 22
    check_color = rgba(0a84ffff)
    fail_color = rgba(ff453aff)
    position = 0, -80
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(ffffffff)
    font_size = 96
    font_family = Adwaita Sans
    position = 0, 110
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(ebebf0dd)
    font_size = 20
    font_family = Adwaita Sans
    position = 0, 20
    halign = center
    valign = center
}
