#!/usr/bin/env python3
"""Write themes/palettes.index — the swatch source for the rice menu.

The menu (SUPER+T) shows four colours next to every rice so you can pick one by
eye rather than by remembering what "duskfox" looked like. Those colours have to
come from somewhere every profile actually has, and the only file all forty-odd
ship is alacritty.toml.

Parsing forty-odd TOML files inside the menu would mean forty-odd FileViews and
a visible delay on a keypress, so it is done here instead and the menu reads one
small file. Re-run after adding or recolouring a rice:

    python3 docs/gen_palette_index.py

Format, one line per rice, '|' separated:

    <name>|<bg>|<fg>|<accent>|<accent2>
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THEMES = os.path.join(REPO, "themes")
LIST = os.path.join(THEMES, "profiles.list")
OUT = os.path.join(THEMES, "palettes.index")

HEX = r'"(#[0-9a-fA-F]{6})"'


def section(text, name):
    """Body of a [name] table, up to the next [ at column 0."""
    m = re.search(r'^\[' + re.escape(name) + r'\]\s*$(.*?)(?=^\[|\Z)',
                  text, re.M | re.S)
    return m.group(1) if m else ""


def key(body, k):
    m = re.search(r'^\s*' + re.escape(k) + r'\s*=\s*' + HEX, body, re.M)
    return m.group(1) if m else None


def palette(rice):
    p = os.path.join(THEMES, rice, "alacritty.toml")
    if not os.path.isfile(p):
        return None
    t = open(p, encoding="utf-8").read()

    primary = section(t, "colors.primary")
    cursor = section(t, "colors.cursor")
    normal = section(t, "colors.normal")
    bright = section(t, "colors.bright")

    bg = key(primary, "background")
    fg = key(primary, "foreground")
    # The cursor is the closest thing every rice has to a declared accent —
    # it is the one colour a theme picks to stand against its own background.
    ac = key(cursor, "cursor")
    # Second swatch: whichever of these the rice defines first, so the pair
    # reads as two different hues rather than two shades of one.
    ac2 = None
    for src in (normal, bright):
        for k in ("blue", "magenta", "cyan", "green", "yellow", "red"):
            v = key(src, k)
            if v and v.lower() not in (str(ac).lower(), str(bg).lower()):
                ac2 = v
                break
        if ac2:
            break

    if not (bg and fg):
        return None
    return bg, fg, ac or fg, ac2 or (ac or fg)


def main():
    names = []
    for line in open(LIST, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        names.append(line.split("|")[0])

    rows, skipped = [], []
    for n in names:
        p = palette(n)
        if p:
            rows.append("|".join((n,) + p))
        else:
            skipped.append(n)

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# generated by docs/gen_palette_index.py — do not edit\n")
        f.write("# <name>|<bg>|<fg>|<accent>|<accent2>\n")
        f.write("\n".join(rows) + "\n")

    print("%d rices -> %s" % (len(rows), OUT))
    if skipped:
        # Not fatal: the menu falls back to the active rice's own colours for
        # anything missing here, so a rice without swatches still appears.
        print("no palette for: %s" % " ".join(skipped), file=sys.stderr)


if __name__ == "__main__":
    main()
